// samples/Huia.TodoApp/src/components/ui/qr-code.tsx
"use client";

import {useEffect, useState} from "react";
import QRCode from "qrcode";

import {cn} from "@/lib/utils";

/** Renders `value` (e.g. an `otpauth://` URI) as a scannable QR code, so setting up an authenticator app
 * doesn't require manually retyping the shared key. */
export function QrCode({value, size = 176, className}: { value: string; size?: number; className?: string }) {
    const [dataUrl, setDataUrl] = useState<string | null>(null);

    useEffect(() => {
        let cancelled = false;
        QRCode.toDataURL(value, {width: size, margin: 1}).then((url) => {
            if (!cancelled) setDataUrl(url);
        });
        return () => {
            cancelled = true;
        };
    }, [value, size]);

    if (!dataUrl) {
        return (
            <div
                className={cn("animate-pulse rounded-md bg-muted", className)}
                style={{width: size, height: size}}
            />
        );
    }

    // eslint-disable-next-line @next/next/no-img-element -- a data: URI can't go through next/image's optimizer
    return <img src={dataUrl} alt="" width={size} height={size} className={cn("rounded-md", className)} />;
}

// samples/Huia.AdminUI/app/components/QrCode.vue
<script setup lang="ts">
import QRCode from 'qrcode'

const props = withDefaults(defineProps<{ value: string, size?: number }>(), { size: 176 })

const dataUrl = ref<string | null>(null)

watch(() => props.value, async (value) => {
  dataUrl.value = await QRCode.toDataURL(value, { width: props.size, margin: 1 })
}, { immediate: true })
</script>

<template>
  <img v-if="dataUrl" :src="dataUrl" :width="size" :height="size" alt="" class="rounded-md">
  <div v-else class="animate-pulse rounded-md bg-elevated" :style="{ width: `${size}px`, height: `${size}px` }" />
</template>
